### PR TITLE
Centralizing images

### PR DESCRIPTION
**Pull request by jonathangaldino**
First, my bad on creating a bunch of weird PR with nothing to really add to the project.

Also, I created a class to centralize images and that class, has justify-content. It should work now.

Thanks.

### CODE REVIEW

**Review by rafaelcn — APPROVED** [review]
It looks like this fixes two issues, I would recommend to you that you create each PR to the respective issue, that's a better option as it separates code that could potentially introduce bugs and a revert would also revert the solution of other issue.

**Comment by rafaelcn** [comment]
Sorry @JohnzBallad, open a new PR with this fix to the master branch of this repository, it looks like you inserted it on `master`.

**Comment by rafaelcn** [comment]
One more thing, adjusting the height of the container has no effect over here.

**Comment by jonathangaldino** [comment]
Oh wait... why 3 files changed? haha
My bad, wasn't supposed to commit derint.css :-1: 
I'll make another PR.

**Pull request merged**
